FROM node:16.19 AS build

WORKDIR /app

# 接收构建时的 API_BASE_URL 参数
ARG VUE_APP_API_BASE_URL
ENV VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL}

COPY vue/package*.json ./
RUN npm install
COPY vue/ ./

# 使用传入的环境变量进行构建
RUN VUE_APP_API_BASE_URL=$VUE_APP_API_BASE_URL npm run build

# 运行阶段
FROM nginx:alpine

# 将自定义的 Nginx 配置文件复制到 Nginx 容器中
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


