FROM node:16.19 AS build

WORKDIR /app

COPY vue/package*.json ./
RUN npm install
COPY vue/ ./
RUN npm run build

# 运行阶段
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
