FROM node:16.19 AS build

WORKDIR /app

COPY vue/package*.json ./
RUN npm install
COPY vue/ ./
RUN npm run build

# 运行阶段
FROM nginx:alpine

# 将自定义的 Nginx 配置文件复制到 Nginx 容器中
# COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
