server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 485010
    url: jdbc:mysql://localhost:3306/study_system?serverTimezone=GMT%2b8
    username: root

mybatis:
  mapper-locations: classpath:mapper/*xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  
