name: Build and Push Docker Image On Release

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.1.0
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  # 使用 GitHub Secrets 来存储 Docker Hub 用户名
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # 使用 GitHub Secrets 来存储 Docker Hub 访问令牌

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11.0.24'
      
    # 缓存 Maven 依赖以加快构建速度
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Copy backend config
      run: |
        cp src/main/resources/application.yaml.example src/main/resources/application.yaml
        sed -i 's/<YOUR_DB_PASSWORD>/password/' src/main/resources/application.yaml

    - name: Build backend
      run: |
        mvn -X clean install
        mvn package

    # 构建并推送后端 Docker 镜像
    - name: Build and push backend Docker image
      uses: docker/build-push-action@v5.2.0
      with:
        context: ./  # Docker 上下文，项目根目录
        file: Dockerfile.backend  # 后端的 Dockerfile
        platforms: linux/amd64,linux/arm64  # 支持的架构
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend-image:${{ github.event.release.tag_name }}  # Docker Hub 上的镜像标签

    # 缓存 Node.js 依赖以加快构建速度
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # 构建并推送前端 Docker 镜像
    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5.2.0
      with:
        context: ./  # Docker 上下文，项目根目录
        file: Dockerfile.frontend  # 前端的 Dockerfile
        platforms: linux/amd64,linux/arm64  # 支持的架构
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-image:${{ github.event.release.tag_name }}  # Docker Hub 上的镜像标签
