name: Build and Push Docker Image On Push

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.1.0
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  # 使用 GitHub Secrets 来存储 Docker Hub 用户名
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # 使用 GitHub Secrets 来存储 Docker Hub 访问令牌

    # Step 5: 构建并推送前端 Docker 镜像
    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5.2.0
      with:
        context: ./  # Docker 上下文，项目根目录
        file: Dockerfile.frontend  # 前端的 Dockerfile
        platforms: linux/amd64,linux/arm64  # 支持的架构
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-image:latest  # Docker Hub 上的镜像标签

    # Step 6: 构建并推送后端 Docker 镜像
    - name: Build and push backend Docker image
      uses: docker/build-push-action@v5.2.0
      with:
        context: ./  # Docker 上下文，项目根目录
        file: Dockerfile.backend  # 后端的 Dockerfile
        platforms: linux/amd64,linux/arm64  # 支持的架构
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend-image:latest  # Docker Hub 上的镜像标签
